### ISSUE TITLE
For new installation, it can't be activated

### ISSUE THREAD

**Issue by sangnguyenplus** [NawrasBukhari/floating-hearts#1]
Check this screenshot:
<img width="1399" alt="image" src="https://github.com/NawrasBukhari/floating-hearts/assets/6972407/40329e8e-f9d0-487e-9290-49b7b02d0948">

**Comment by NawrasBukhari** [comment]
Fixed https://github.com/NawrasBukhari/floating-hearts/releases/tag/1.0.1
please update the plugin from the admin panel

**Comment by NawrasBukhari** [comment]
Any idea of how to make the enable/disable toggle work properly?

**Comment by sangnguyenplus** [comment]
Hi,

Please check this PR https://github.com/NawrasBukhari/floating-hearts/pull/2

**Comment by NawrasBukhari** [comment]
Thank You! @sangnguyenplus
